name: Daily Scrape

# Schedule to run every day at 7:00 UTC
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: # allows manual triggering

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24' # or whichever version you need

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install playwright
        run: pnpm dlx playwright install

      - name: Run script
        run: node index.js

      - name: Upload scraped file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: result.txt

